# DATA_DIR: '/Users/nsveinsson/Documents/datasets/vmr/' #, MICCAI_AVT_Data

DATASET_NAME: 'other' #'vmr' # or other 'other'
VALIDATION_PROP: 0.1

IMG_EXT: '.mha' #'.nii.gz' #'.mha' #'.nii.gz' #'.mha' #'.nii.gz' # Image file extension

BINARIZE: True # Need true for VMR since 255 labels
ANATOMY: ['ALL'] # can be 'ALL' or ['Aorta', 'Abdominal Aorta', 'Pulmonary', 'Coronary', 'CHD', 'Cerebro']
OUTLET_CLASSES: [0,1,2,3,4,5,6,7,8,9,10]
SCALED: False
CROPPED: False

EXTRACT_VOLUMES: False
ROTATE_VOLUMES: False

RESAMPLE_VOLUMES: False
RESAMPLE_SIZE: [64, 64, 64]

AUGMENT_VOLUMES: False

WRITE_SAMPLES: True
WRITE_IMG: False
REMOVE_OTHER: False # Remove other unconnected vessels in gt volume, can cause problems where vessels are close
WRITE_SURFACE: True
WRITE_CENTERLINE: False
WRITE_VOXEL_PYRAMID: False

WRITE_DISCRETE_CENTERLINE: False
DISCRETE_CENTERLINE_N_POINTS: 10

WRITE_OUTLET_STATS: False
WRITE_OUTLET_IMG: False
UPSAMPLE_OUTLET_IMG: False

WRITE_CROSS_SECTIONAL: False
NUM_CROSS_SECTIONS: 2  # multiples of 2
RESAMPLE_CROSS_IMG: 400
WRITE_TRAJECTORIES: False
N_SLICES: 20

WRITE_VTK: False
WRITE_VTK_THROWOUT: False

MOVE_DIST: 2 # 1.5 how far to move along centerline between sampling, in terms of radius
SIZE_RADIUS: 5 # how big a volume to sample, x radius at each location
RADIUS_ADD: 0.05 # how much to add to radius values (to correct bias) done before scale
RADIUS_SCALE: 1 # how much to add to radius values (to correct bias)

CAPFREE: False # whether to require a certain amount of cap-free volume
CAPFREE_PROP: 0.0 # how much of volume must be cap free, per sidelength
MIN_DIM: 5 # minimum number of voxels in each dimension for subvolume extraction
MOVE_SLOWER_LARGE: 0.5  #0.5 how much slower for bigger vessels
MU_SIZE: 5 # mean for subvolume-radius ratio
SIGMA_SIZE: 0.8 # standard deviation for subvolume-radius ratio
MU_SHIFT: 0 # mean for subvolume shift off centerline
SIGMA_SHIFT: 0.8 # standard deviation for subvolume shift off centerline
NUMBER_SAMPLES: 1 # 2 how many samples to take at each point along vessel
NUMBER_SAMPLES_BIFURC: 1 # 3 how many samples to take if it's a bifurcation
NUMBER_SAMPLES_START: 1 # 5 how many samples to take at start of vessel (first 5%), better for initialization + bifurcations if not processed
MOVE_SLOWER_BIFURC: 1 # 0.1 how much slower for bigger vessels

# Which cases to use for testing
TEST_CASES:
  - '0063_0001'
  - '0076_1001'
  - '0083_2002'
  # - '0100_0002' # No centerline
  # - '0113_0003' # No centerline
  # - '0121_0000'
  - '0134_0002'
  - '0157_0000'
  - '0183_1002'
  - 'KDR32_aorta'
  - 'O150323_2009_aorta'
  - 'SU0269'

# Which cases not to use in extraction
BAD_CASES:
  - '0100_0002' # No centerline
  - '0113_0003' # No centerline
  - '0092_0001' # Aorta with weird dimensions
  - '0064_1001' # Aorta with additional vessels
  - '0065_1001' # Aorta with additional vessels
  - '0140_2001' #AortofemoralCT
  - '0078_0001' #CerebroMR
  - '0079_0001' #CerebroMR
  - '0166_0001' #CerebroMR
  - '0167_0001' #CerebroMR
